# Generated by Django 6.1.1 on 2026-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Character Name')),
                ('hp', models.IntegerField(default=100, verbose_name='Character HP')),
                ('damage', models.FloatField(default=10.0, verbose_name='Character Damage')),
            ],
        ),
    ]
