# Generated by Django 6.1.1 on 2026-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Enemy Name')),
                ('hp', models.IntegerField(default=30, verbose_name='Enemy Current HP')),
                ('max_hp', models.IntegerField(default=30, verbose_name='Enemy MAX HP')),
                ('damage', models.FloatField(default=5.0, verbose_name='Enemy Damage')),
                ('reward_exp', models.IntegerField(default=5, verbose_name='Enemy Reward EXP')),
                ('reward_gold', models.IntegerField(default=10, verbose_name='Enemy Reward Gold')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='Character EXP'),
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='Character Gold'),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Character Level'),
        ),
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=100, verbose_name='Character Max HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=100, verbose_name='Character Current HP'),
        ),
    ]
