# Generated by Django 6.1.1 on 2026-09-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_enemy_character_exp_character_gold_character_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='enemy_hp',
            field=models.IntegerField(default=5, verbose_name='Character Current HP'),
        ),
        migrations.AddField(
            model_name='character',
            name='enemy_name',
            field=models.CharField(default='Zombie', max_length=100, verbose_name='Name of Current Enemy'),
        ),
    ]
