# Generated by Django 6.1.1 on 2026-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_user_alter_character_enemy_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('cost', models.IntegerField(default=100, verbose_name='Item Cost')),
                ('stat_up', models.CharField(max_length=100, verbose_name='Item Stat Up')),
            ],
        ),
    ]
