# Generated by Django 6.1.1 on 2026-09-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased at')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character', verbose_name='Item Owner')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Item Name')),
            ],
        ),
    ]
