# Generated by Django 6.1.1 on 2026-09-13 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character', verbose_name='Store offer for')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='Item Name')),
            ],
        ),
    ]
