# Generated by Django 6.1.1 on 2026-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_shopoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='store_refresh_cost',
            field=models.IntegerField(default=10, verbose_name='Character Store Refresh Cost'),
        ),
    ]
