# Generated by Django 6.1.1 on 2026-09-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_character_store_refresh_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp_to_new_level',
            field=models.IntegerField(default=100, verbose_name='Character XP To New Level'),
        ),
    ]
