# Generated by Django 6.1.1 on 2026-09-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_character_exp_to_new_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='enemy_name',
        ),
        migrations.AddField(
            model_name='character',
            name='current_enemy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.enemy', verbose_name='Name of Current Enemy'),
        ),
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='Character EXP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gold',
            field=models.PositiveIntegerField(default=0, verbose_name='Character Gold'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.PositiveIntegerField(default=100, verbose_name='Character Current HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='max_hp',
            field=models.PositiveIntegerField(default=100, verbose_name='Character Max HP'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Character Name'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.PositiveIntegerField(default=30, verbose_name='Enemy Current HP'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='max_hp',
            field=models.PositiveIntegerField(default=30, verbose_name='Enemy MAX HP'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='reward_exp',
            field=models.PositiveIntegerField(default=5, verbose_name='Enemy Reward EXP'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='reward_gold',
            field=models.PositiveIntegerField(default=10, verbose_name='Enemy Reward Gold'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(default=100, verbose_name='Item Cost'),
        ),
    ]
