# Generated by Django 6.1.1 on 2026-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_character_enemy_name_character_current_enemy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='stat_up',
        ),
        migrations.AddField(
            model_name='item',
            name='click_damage_bonus',
            field=models.IntegerField(default=0, verbose_name='Item CLICK Damage Bonus'),
        ),
        migrations.AddField(
            model_name='item',
            name='dps_bonus',
            field=models.IntegerField(default=0, verbose_name='Item DPS Damage Bonus'),
        ),
        migrations.AddField(
            model_name='item',
            name='hp_bonus',
            field=models.IntegerField(default=0, verbose_name='Item HP Damage Bonus'),
        ),
    ]
