# Generated by Django 6.1.1 on 2026-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_item_stat_up_item_click_damage_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='damage',
            new_name='base_click_damage',
        ),
        migrations.AddField(
            model_name='character',
            name='base_dps_damage',
            field=models.FloatField(default=0.0, verbose_name='Character DPS Damage'),
        ),
    ]
