# Generated by Django 6.1.1 on 2026-09-18 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_rename_damage_character_base_click_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_dps_tick_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Character Last DPS Tick Time'),
        ),
    ]
