# Generated by Django 6.1.1 on 2026-09-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_character_last_dps_tick_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(verbose_name='Game Log Text')),
                ('category', models.CharField(choices=[('combat', 'Бой'), ('economy', 'Экономика'), ('system', 'Система')], default='combat', max_length=20, verbose_name='Game Log Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Game Log Created')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character', verbose_name='Game Log Person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
